######################################################################
# Automatically generated by qmake (3.0) Wed Oct 26 11:44:53 2016
######################################################################

TEMPLATE = app
TARGET = rw_task
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    rwthread.cpp

HEADERS += \
    rwthread.h
